### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by doggobot-owner** [dapper-gh/image-host#4]
c:\host>node .
```
internal/util.js:268
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at Object.promisify (internal/util.js:268:11)
    at Object.<anonymous> (c:\host\index.js:61:29)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
```
what happened?

**Comment by dapper-gh** [comment]
Hi! Thanks for reporting this issue. This would suggest that `require("crypto").randomInt` does not exist. Can you run `node -v` in your terminal and paste the output here?

**Comment by doggobot-owner** [comment]
v12.1.0

**Comment by dapper-gh** [comment]
> v12.1.0

The `crypto.randomInt` function was added in `v14.10.0` and `v12.19.0`. ([source](https://stackoverflow.com/questions/33609404/node-js-how-to-generate-random-numbers-in-specific-range-using-crypto-randomby/65291915#65291915)). You'll need to update your Node to one of those versions (or a later version) to run the image host. Since you're on Windows, I believe you can do this by going to https://nodejs.org/ and downloading the latest version.
