### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by Sintzy** [dapper-gh/image-host#7]
`Error: ENOENT: no such file or directory, open 'cert/key.pem'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /home/runner/xerecapt/index.js:577:13
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)`

**Comment by dapper-gh** [comment]
Hi! With no further context, I can only assume that you've set the certificate file in `config.js` to a file which does not exist.

**Comment by Sintzy** [comment]
> Hi! With no further context, I can only assume that you've set the certificate file in `config.js` to a file which does not exist.

thanks :)
