### ISSUE TITLE
it wont upload help btw im using a vps to host it

### ISSUE THREAD

**Issue by laginnovoline** [dapper-gh/image-host#8]
Error message:
The remote server returned an error: (404) Not Found.

Request URL:
https://ppware.cf/upload

Status code:
(404) Not Found

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
CF-Cache-Status: DYNAMIC
cf-request-id: 09f41293e500001cf22d0f4000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=ww9MRwd3V%2F7FQDeMsEkRFIV0vruxcbBQodSGEA9KkBaVnGHha%2B5SZBc%2BHj0cAO4V8tCyL3QobECjXeRnQ%2BKcRVcG3VJxMEJJlEU%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
CF-RAY: 64cd206619591cf2-BUD
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
Content-Type: text/html; charset=iso-8859-1
Date: Sun, 09 May 2021 18:52:43 GMT
Set-Cookie: __cfduid=df49c328305023a57865fc78371fe67961620586363; expires=Tue, 08-Jun-21 18:52:43 GMT; path=/; domain=.ppware.cf; HttpOnly; SameSite=Lax; Secure
Server: cloudflare

Response text:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.46 (Win64) OpenSSL/1.1.1j PHP/8.0.3 Server at ppware.cf Port 80</address>
</body></html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by dapper-gh** [comment]
This is an Apache error and has nothing to do with any software I produce.
